### ISSUE TITLE
Coverting STAR files to CSV: TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by charbj** [tbepler/topaz#1]
For those looking, while using the `topaz star_to_coordinates XXX.star` function. I found this little bug while trying to process a star file of the following format:

```
data_
loop_ 
_rlnMicrographName #1
_rlnCoordinateX #2 
_rlnCoordinateY #3 
2100.mrc  435.000000  1925.000000
2100.mrc  485.000000  1615.000000
...
```

```
Traceback (most recent call last):
  File "/usr/local/programs/anaconda2/bin/topaz", line 11, in <module>
    sys.exit(main())
  File "/usr/local/programs/anaconda2/lib/python2.7/site-packages/topaz/main.py", line 116, in main
    args.func(args)
  File "/usr/local/programs/anaconda2/lib/python2.7/site-packages/topaz/commands/star_to_coordinates.py", line 74, in main
    table = table[['rlnMicrographName', 'rlnCoordinateX', 'rlnCoordinateY']]
TypeError: 'NoneType' object has no attribute '__getitem__'format:
```

I simply edited line 22 in `star_to_coordinates.py` from 

```
def parse_star(f):
    lines = f.readlines()
    for i in range(len(lines)):
        line = lines[i]
        if line.startswith('data_image'):   # Assumes old format?
            return parse_star_body(lines[i+1:])
```

to

```
def parse_star(f):
    lines = f.readlines()
    for i in range(len(lines)):
        line = lines[i]
        if line.startswith('data_'):        # Should fix.
            return parse_star_body(lines[i+1:])
```

Happy picking!

**Comment by tbepler** [comment]
Thanks for bringing this to my attention. I just updated the master branch to include this fix.
