### ISSUE TITLE
TypeError using Topaz denoise

### ISSUE THREAD

**Issue by bencreekm** [tbepler/topaz#119]
I am using topaz denoise on my own dataset following the denoising tutorial. I keep getting an error that I am not sure how to fix. 
Do you know what may be going wrong? Thanks!

version: Topaz 0.2.4

My command is: topaz denoise -a denoised/training_data/partA/ -b denoised/training_data/partB/

The error is: 
Traceback (most recent call last):
  File "/usr/local/EMAN2/eman2-sphire-sparx/envs/topaz/bin/topaz", line 11, in <module>
    load_entry_point('topaz-em==0.2.4', 'console_scripts', 'topaz')()
  File "/usr/local/EMAN2/eman2-sphire-sparx/envs/topaz/lib/python3.6/site-packages/topaz/main.py", line 148, in main
    args.func(args)
  File "/usr/local/EMAN2/eman2-sphire-sparx/envs/topaz/lib/python3.6/site-packages/topaz/commands/denoise.py", line 535, in main
    if not os.path.exists(args.output):
  File "/usr/local/EMAN2/eman2-sphire-sparx/envs/topaz/lib/python3.6/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by bencreekm** [comment]
Update: This issue does go away if you include the -o flag
