### ISSUE TITLE
ImportError: (...)/libmkldnn.so.0: undefined symbol: cblas_sgemm_alloc

### ISSUE THREAD

**Issue by lucajovine** [tbepler/topaz#152]
Hello, after updating to 0.2.5, I am getting:

```
(topaz) > topaz --help
Traceback (most recent call last):
  File "/usr/local/conda/miniconda3/envs/topaz/bin/topaz", line 33, in <module>
    sys.exit(load_entry_point('topaz-em==0.2.5', 'console_scripts', 'topaz')())
  File "/usr/local/conda/miniconda3/envs/topaz/lib/python3.6/site-packages/topaz/main.py", line 60, in main
    import topaz.commands.train
  File "/usr/local/conda/miniconda3/envs/topaz/lib/python3.6/site-packages/topaz/commands/train.py", line 12, in <module>
    import torch
  File "/usr/local/conda/miniconda3/envs/topaz/lib/python3.6/site-packages/torch/__init__.py", line 84, in <module>
    from torch._C import *
ImportError: /usr/local/conda/miniconda3/envs/topaz/lib/python3.6/site-packages/torch/lib/libmkldnn.so.0: undefined symbol: cblas_sgemm_alloc
(topaz) >
```

Unfortunately, the "conda install -c anaconda mkl" or "conda install -c intel mkl" solutions reported elsewhere here do not seem to help...

**Comment by lucajovine** [comment]
Hi again, creating the environment with python 3.10 (instead of 3.6) solved the problem:

```
conda create -n topaz python=3.10
```
