### ISSUE TITLE
`topaz preprocess --scale 1` produces numpy error

### ISSUE THREAD

**Issue by alexjnoble** [tbepler/topaz#16]
Changing --scale from 1 to 2 solves the problem:

**[node48 ~]$** /gpfs/sw/bin/topaz preprocess /my/files/training_images/*mrc --scale 1 --num-workers -1 --format mrc,png --pixel-sampling 25 --niters 200 --seed 1 --verbose --destdir /my/files/training_images/pre

WARNING: Could not find the Nvidia SMI binary to bind into container

 [1 of 32] downsampled: gr1_00001gr_00007sq_v02_00006hln_v01_pixelsize63.68

 [2 of 32] downsampled: gr1_00021gr_00024sq_v02_00008hln_v01_pixelsize63.68

 [3 of 32] downsampled: gr1a_00011gr_00054sq_v02_00003hln_v01_pixelsize63.68

 [4 of 32] downsampled: gr1a_00011gr_00055sq_v02_00004hln_v02_pixelsize63.68

 [5 of 32] downsampled: gr1a_00017gr_00005sq_v02_00005hln_v01_pixelsize63.68

 [6 of 32] downsampled: gr1a_00017gr_00006sq_v02_pixelsize246.24

 [7 of 32] downsampled: gr1a_00017gr_00017sq_v01_pixelsize246.24

 [8 of 32] downsampled: gr1a_00021gr_00002sq_v02_pixelsize246.24

 [9 of 32] downsampled: ps2_00001gr_00021sq_v02_00015hln_pixelsize92.60

 [10 of 32] downsampled: ps2_00002gr_pixelsize4069.76

 [11 of 32] downsampled: ps2_00006gr_00030sq_v02_00015hln_v01_pixelsize92.60

 [12 of 32] downsampled: ps2_00009gr_00015sq_v02_00009hln_pixelsize92.60

 [13 of 32] downsampled: ps2_00016gr_00007sq_v01_pixelsize208.88

 [14 of 32] downsampled: ps2_00023gr_00022sq_v01_pixelsize208.88

 [15 of 32] downsampled: ps2_00023gr_00024sq_pixelsize208.88

 [16 of 32] downsampled: ps2_00023gr_pixelsize4069.76

 [17 of 32] downsampled: gr9_00030gr_00008sq_v01_00002hl_pixelsize70.68

 [18 of 32] downsampled: gr9_00030gr_00011sq_pixelsize370.88

 [19 of 32] downsampled: grid1_00009gr_pixelsize4069.76

 [20 of 32] downsampled: grid2_00005gr_00001sq_v02_00004hln

 [21 of 32] downsampled: grid4_00016gr_00001sq_v02_00002hln_v02_pixelsize130.55

 [22 of 32] downsampled: grid4_00018gr_00034sq_pixelsize208.88

 [23 of 32] downsampled: grid4_00021gr_00043sq_v01_pixelsize208.88

 [24 of 32] downsampled: grid4_00022gr_pixelsize4069.76

 [25 of 32] downsampled: grid1_00008gr_pixelsize3327.60

 [26 of 32] downsampled: grid1_00012gr_00051sq_pixelsize246.82

 [27 of 32] downsampled: grid1_00015gr_00058sq_pixelsize246.82

 [28 of 32] downsampled: grid1_00016gr_00002sq_00001hl_pixelsize173.21

 [29 of 32] downsampled: grid1_00022gr_00010sq_v01_00002hl_pixelsize_173.21

 [30 of 32] downsampled: grid1_00030gr_pixelsize3327.60

 [31 of 32] downsampled: gold_00002gr_pixelsize4069.76

 [32 of 32] downsampled: negstain_00025gr_pixelsize3240.00

 fit scaled GMM, niters=200, sample=25, seed=1

Traceback (most recent call last):

  File "/usr/local/anaconda3/envs/topazenv/bin/topaz", line 11, in <module>

    load_entry_point('topaz==0.1.0', 'console_scripts', 'topaz')()

  File "/usr/local/anaconda3/envs/topazenv/lib/python3.6/site-packages/topaz-0.1.0-py3.6.egg/topaz/main.py", line 144, in main

    args.func(args)

  File "/usr/local/anaconda3/envs/topazenv/lib/python3.6/site-packages/topaz-0.1.0-py3.6.egg/topaz/commands/preprocess.py", line 120, in main

    images, metadata = sgmm_scaling(images, niters, samples, seed, verbose) 

  File "/usr/local/anaconda3/envs/topazenv/lib/python3.6/site-packages/topaz-0.1.0-py3.6.egg/topaz/commands/preprocess.py", line 72, in sgmm_scaling

    Xsample = [x.ravel()[::sample] for x in X]

  File "/usr/local/anaconda3/envs/topazenv/lib/python3.6/site-packages/topaz-0.1.0-py3.6.egg/topaz/commands/preprocess.py", line 72, in <listcomp>

    Xsample = [x.ravel()[::sample] for x in X]

AttributeError: 'Image' object has no attribute 'ravel'

**[node48 ~]$** /gpfs/sw/bin/topaz preprocess /my/files/training_images/*mrc --scale 2 --num-workers -1 --format mrc,png --pixel-sampling 25 --niters 200 --seed 1 --verbose --destdir /my/files/training_images/pre

WARNING: Could not find the Nvidia SMI binary to bind into container

 [1 of 32] downsampled: gr1_00001gr_00007sq_v02_00006hln_v01_pixelsize63.68

 [2 of 32] downsampled: gr1_00021gr_00024sq_v02_00008hln_v01_pixelsize63.68

 [3 of 32] downsampled: gr1a_00011gr_00054sq_v02_00003hln_v01_pixelsize63.68

 [4 of 32] downsampled: gr1a_00011gr_00055sq_v02_00004hln_v02_pixelsize63.68

 [5 of 32] downsampled: gr1a_00017gr_00005sq_v02_00005hln_v01_pixelsize63.68

 [6 of 32] downsampled: gr1a_00017gr_00006sq_v02_pixelsize246.24

 [7 of 32] downsampled: gr1a_00017gr_00017sq_v01_pixelsize246.24

 [8 of 32] downsampled: gr1a_00021gr_00002sq_v02_pixelsize246.24

 [9 of 32] downsampled: ps2_00001gr_00021sq_v02_00015hln_pixelsize92.60

 [10 of 32] downsampled: ps2_00002gr_pixelsize4069.76

 [11 of 32] downsampled: ps2_00006gr_00030sq_v02_00015hln_v01_pixelsize92.60

 [12 of 32] downsampled: ps2_00009gr_00015sq_v02_00009hln_pixelsize92.60

 [13 of 32] downsampled: ps2_00016gr_00007sq_v01_pixelsize208.88

 [14 of 32] downsampled: ps2_00023gr_00022sq_v01_pixelsize208.88

 [15 of 32] downsampled: ps2_00023gr_00024sq_pixelsize208.88

 [16 of 32] downsampled: ps2_00023gr_pixelsize4069.76

 [17 of 32] downsampled: gr9_00030gr_00008sq_v01_00002hl_pixelsize70.68

 [18 of 32] downsampled: gr9_00030gr_00011sq_pixelsize370.88

 [19 of 32] downsampled: grid1_00009gr_pixelsize4069.76

 [20 of 32] downsampled: grid2_00005gr_00001sq_v02_00004hln

 [21 of 32] downsampled: grid4_00016gr_00001sq_v02_00002hln_v02_pixelsize130.55

 [22 of 32] downsampled: grid4_00018gr_00034sq_pixelsize208.88

 [23 of 32] downsampled: grid4_00021gr_00043sq_v01_pixelsize208.88

 [24 of 32] downsampled: grid4_00022gr_pixelsize4069.76

 [25 of 32] downsampled: grid1_00008gr_pixelsize3327.60

 [26 of 32] downsampled: grid1_00012gr_00051sq_pixelsize246.82

 [27 of 32] downsampled: grid1_00015gr_00058sq_pixelsize246.82

 [28 of 32] downsampled: grid1_00016gr_00002sq_00001hl_pixelsize173.21

 [29 of 32] downsampled: grid1_00022gr_00010sq_v01_00002hl_pixelsize_173.21

 [30 of 32] downsampled: grid1_00030gr_pixelsize3327.60

 [31 of 32] downsampled: gold_00002gr_pixelsize4069.76

 [32 of 32] downsampled: negstain_00025gr_pixelsize3240.00

 fit scaled GMM, niters=200, sample=25, seed=1

 [000] logp=-2820459.6133811227

 [001] logp=-2806864.78066376

 [002] logp=-2806819.454160788

 [003] logp=-2806814.8822830096

 [004] logp=-2806806.411051859

 [005] logp=-2806793.5246113804

 [006] logp=-2806787.9846159355

 [007] logp=-2806808.928660144

 logp tolerance reached

 weights: [0.501386273757172, 0.49861372624282796]

 means: [4737.694066615208, 4829.18809045471]

 variances: [7306609.740475055, 8764106.58159098]

 saving: /my/files/training_images/pre/gr1_00001gr_00007sq_v02_00006hln_v01_pixelsize63.68.mrc

 saving: /my/files/training_images/pre/gr1_00001gr_00007sq_v02_00006hln_v01_pixelsize63.68.png

 saving: /my/files/training_images/pre/gr1_00021gr_00024sq_v02_00008hln_v01_pixelsize63.68.mrc

 saving: /my/files/training_images/pre/gr1_00021gr_00024sq_v02_00008hln_v01_pixelsize63.68.png

 saving: /my/files/training_images/pre/gr1a_00011gr_00054sq_v02_00003hln_v01_pixelsize63.68.mrc

 saving: /my/files/training_images/pre/gr1a_00011gr_00054sq_v02_00003hln_v01_pixelsize63.68.png

 saving: /my/files/training_images/pre/gr1a_00011gr_00055sq_v02_00004hln_v02_pixelsize63.68.mrc

 saving: /my/files/training_images/pre/gr1a_00011gr_00055sq_v02_00004hln_v02_pixelsize63.68.png

 saving: /my/files/training_images/pre/gr1a_00017gr_00005sq_v02_00005hln_v01_pixelsize63.68.mrc

 saving: /my/files/training_images/pre/gr1a_00017gr_00005sq_v02_00005hln_v01_pixelsize63.68.png

 saving: /my/files/training_images/pre/gr1a_00017gr_00006sq_v02_pixelsize246.24.mrc

 saving: /my/files/training_images/pre/gr1a_00017gr_00006sq_v02_pixelsize246.24.png

 saving: /my/files/training_images/pre/gr1a_00017gr_00017sq_v01_pixelsize246.24.mrc

 saving: /my/files/training_images/pre/gr1a_00017gr_00017sq_v01_pixelsize246.24.png

 saving: /my/files/training_images/pre/gr1a_00021gr_00002sq_v02_pixelsize246.24.mrc

 saving: /my/files/training_images/pre/gr1a_00021gr_00002sq_v02_pixelsize246.24.png

 saving: /my/files/training_images/pre/ps2_00001gr_00021sq_v02_00015hln_pixelsize92.60.mrc

 saving: /my/files/training_images/pre/ps2_00001gr_00021sq_v02_00015hln_pixelsize92.60.png

 saving: /my/files/training_images/pre/ps2_00002gr_pixelsize4069.76.mrc

 saving: /my/files/training_images/pre/ps2_00002gr_pixelsize4069.76.png

 saving: /my/files/training_images/pre/ps2_00006gr_00030sq_v02_00015hln_v01_pixelsize92.60.mrc

 saving: /my/files/training_images/pre/ps2_00006gr_00030sq_v02_00015hln_v01_pixelsize92.60.png

 saving: /my/files/training_images/pre/ps2_00009gr_00015sq_v02_00009hln_pixelsize92.60.mrc

 saving: /my/files/training_images/pre/ps2_00009gr_00015sq_v02_00009hln_pixelsize92.60.png

 saving: /my/files/training_images/pre/ps2_00016gr_00007sq_v01_pixelsize208.88.mrc

 saving: /my/files/training_images/pre/ps2_00016gr_00007sq_v01_pixelsize208.88.png

 saving: /my/files/training_images/pre/ps2_00023gr_00022sq_v01_pixelsize208.88.mrc

 saving: /my/files/training_images/pre/ps2_00023gr_00022sq_v01_pixelsize208.88.png

 saving: /my/files/training_images/pre/ps2_00023gr_00024sq_pixelsize208.88.mrc

 saving: /my/files/training_images/pre/ps2_00023gr_00024sq_pixelsize208.88.png

 saving: /my/files/training_images/pre/ps2_00023gr_pixelsize4069.76.mrc

 saving: /my/files/training_images/pre/ps2_00023gr_pixelsize4069.76.png

 saving: /my/files/training_images/pre/gr9_00030gr_00008sq_v01_00002hl_pixelsize70.68.mrc

 saving: /my/files/training_images/pre/gr9_00030gr_00008sq_v01_00002hl_pixelsize70.68.png

 saving: /my/files/training_images/pre/gr9_00030gr_00011sq_pixelsize370.88.mrc

 saving: /my/files/training_images/pre/gr9_00030gr_00011sq_pixelsize370.88.png

 saving: /my/files/training_images/pre/grid1_00009gr_pixelsize4069.76.mrc

 saving: /my/files/training_images/pre/grid1_00009gr_pixelsize4069.76.png

 saving: /my/files/training_images/pre/grid2_00005gr_00001sq_v02_00004hln.mrc

 saving: /my/files/training_images/pre/grid2_00005gr_00001sq_v02_00004hln.png

 saving: /my/files/training_images/pre/grid4_00016gr_00001sq_v02_00002hln_v02_pixelsize130.55.mrc

 saving: /my/files/training_images/pre/grid4_00016gr_00001sq_v02_00002hln_v02_pixelsize130.55.png

 saving: /my/files/training_images/pre/grid4_00018gr_00034sq_pixelsize208.88.mrc

 saving: /my/files/training_images/pre/grid4_00018gr_00034sq_pixelsize208.88.png

 saving: /my/files/training_images/pre/grid4_00021gr_00043sq_v01_pixelsize208.88.mrc

 saving: /my/files/training_images/pre/grid4_00021gr_00043sq_v01_pixelsize208.88.png

 saving: /my/files/training_images/pre/grid4_00022gr_pixelsize4069.76.mrc

 saving: /my/files/training_images/pre/grid4_00022gr_pixelsize4069.76.png

 saving: /my/files/training_images/pre/grid1_00008gr_pixelsize3327.60.mrc

 saving: /my/files/training_images/pre/grid1_00008gr_pixelsize3327.60.png

 saving: /my/files/training_images/pre/grid1_00012gr_00051sq_pixelsize246.82.mrc

 saving: /my/files/training_images/pre/grid1_00012gr_00051sq_pixelsize246.82.png

 saving: /my/files/training_images/pre/grid1_00015gr_00058sq_pixelsize246.82.mrc

 saving: /my/files/training_images/pre/grid1_00015gr_00058sq_pixelsize246.82.png

 saving: /my/files/training_images/pre/grid1_00016gr_00002sq_00001hl_pixelsize173.21.mrc

 saving: /my/files/training_images/pre/grid1_00016gr_00002sq_00001hl_pixelsize173.21.png

 saving: /my/files/training_images/pre/grid1_00022gr_00010sq_v01_00002hl_pixelsize_173.21.mrc

 saving: /my/files/training_images/pre/grid1_00022gr_00010sq_v01_00002hl_pixelsize_173.21.png

 saving: /my/files/training_images/pre/grid1_00030gr_pixelsize3327.60.mrc

 saving: /my/files/training_images/pre/grid1_00030gr_pixelsize3327.60.png

 saving: /my/files/training_images/pre/gold_00002gr_pixelsize4069.76.mrc

 saving: /my/files/training_images/pre/gold_00002gr_pixelsize4069.76.png

 saving: /my/files/training_images/pre/negstain_00025gr_pixelsize3240.00.mrc

 saving: /my/files/training_images/pre/negstain_00025gr_pixelsize3240.00.png

 saving metadata: /my/files/training_images/pre/metadata.json

**[node48 ~]$**

**Comment by tbepler** [comment]
Thanks for the bug report. Fixed in commit bd2ae5e40bebbac7b4f76a6210016f44dade4894
