### ISSUE TITLE
Version 0.3.1 doesn't install cleanly

### ISSUE THREAD

**Issue by Guillawme** [tbepler/topaz#212]
Hello,

I just tried installing version 0.3.1 in three different ways, and none of them worked... I got missing dependencies, and installing them with conda ends up in a dead end.

If I didn't follow the correct procedure, and the installation of 0.3.1 can actually work, then the correct procedure should be explained in the README. If the installation of this version is broken (as I suspect), then of course it should be fixed and documented (if different than what is already in the README).

Details of what I tried below:

# Attempt 1

I followed the current instructions in the README, under the "recommended" section:

```bash
conda create -n topaz-0.3.1-python-3.6 python=3.6
conda activate topaz-0.3.1-python-3.6
conda install topaz -c tbepler -c pytorch
```

<details>

```bash
(topaz-0.3.1-python-3.6) [guillaume@ANG-KEMI23102LP ~]$ topaz --version
Traceback (most recent call last):
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/bin/topaz", line 10, in <module>
    from importlib.metadata import distribution
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/bin/topaz", line 13, in <module>
    from importlib_metadata import distribution
ModuleNotFoundError: No module named 'importlib_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/bin/topaz", line 15, in <module>
    from pkg_resources import load_entry_point
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3242, in <module>
    @_call_aside
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'h5py' distribution was not found and is required by topaz-em
```

I installed `h5py` with conda and retried:

```bash
(topaz-0.3.1-python-3.6) [guillaume@ANG-KEMI23102LP ~]$ topaz --version
Traceback (most recent call last):
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/bin/topaz", line 10, in <module>
    from importlib.metadata import distribution
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/bin/topaz", line 13, in <module>
    from importlib_metadata import distribution
ModuleNotFoundError: No module named 'importlib_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/bin/topaz", line 15, in <module>
    from pkg_resources import load_entry_point
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3242, in <module>
    @_call_aside
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'tqdm' distribution was not found and is required by topaz-em
```

I installed `tqdm` with conda and retried:

``` bash
(topaz-0.3.1-python-3.6) [guillaume@ANG-KEMI23102LP ~]$ topaz --version
Traceback (most recent call last):
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/bin/topaz", line 10, in <module>
    from importlib.metadata import distribution
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/bin/topaz", line 13, in <module>
    from importlib_metadata import distribution
ModuleNotFoundError: No module named 'importlib_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/bin/topaz", line 15, in <module>
    from pkg_resources import load_entry_point
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3242, in <module>
    @_call_aside
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/miniconda3/envs/topaz-0.3.1-python-3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'importlib-resources; python_version < "3.7"' distribution was not found and is required by tqdm
```

I tried to install `importlib-resources`, but it is apparently incompatible with `python=3.6`:

```bash
(topaz-0.3.1-python-3.6) [guillaume@ANG-KEMI23102LP ~]$ conda install importlib-resources
Channels:
 - defaults
 - pytorch
 - tbepler
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: - warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package importlib-resources-6.1.1-pyhd3eb1b0_1 requires importlib_resources >=6.1.1,<6.1.2.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ importlib-resources is installable with the potential options
│  ├─ importlib-resources 6.1.1 would require
│  │  └─ importlib_resources 6.1.1 py312h06a4308_0, which requires
│  │     └─ python >=3.12,<3.13.0a0 , which can be installed;
│  ├─ importlib-resources 6.1.1 would require
│  │  └─ importlib_resources >=6.1.1,<6.1.2.0a0  with the potential options
│  │     ├─ importlib_resources [6.1.1|6.4.0] would require
│  │     │  └─ python >=3.10,<3.11.0a0 , which can be installed;
│  │     ├─ importlib_resources [6.1.1|6.4.0] would require
│  │     │  └─ python >=3.11,<3.12.0a0 , which can be installed;
│  │     ├─ importlib_resources [6.1.1|6.4.0], which can be installed (as previously explained);
│  │     ├─ importlib_resources [6.1.1|6.4.0] would require
│  │     │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  │     └─ importlib_resources [6.1.1|6.4.0] would require
│  │        └─ python >=3.9,<3.10.0a0 , which can be installed;
│  └─ importlib-resources 6.4.0 would require
│     └─ importlib_resources >=6.4.0,<6.4.1.0a0  with the potential options
│        ├─ importlib_resources [6.1.1|6.4.0], which can be installed (as previously explained);
│        ├─ importlib_resources [6.1.1|6.4.0], which can be installed (as previously explained);
│        ├─ importlib_resources [6.1.1|6.4.0], which can be installed (as previously explained);
│        ├─ importlib_resources [6.1.1|6.4.0], which can be installed (as previously explained);
│        ├─ importlib_resources [6.1.1|6.4.0], which can be installed (as previously explained);
│        └─ importlib_resources 6.4.0 would require
│           └─ python >=3.13,<3.14.0a0 , which can be installed;
└─ pin-1 is not installable because it requires
   └─ python 3.6.* , which conflicts with any installable versions previously reported.
```

</details>

# Attempt 2

In a new conda env, I tried installing topaz-0.3.1 directly, without first specifying a python version, hoping dependencies are correctly specified so that conda will figure out what works:

```bash
conda create -n topaz-0.3.1-python-auto
conda activate topaz-0.3.1-python-auto
conda install topaz -c tbepler -c pytorch
```

<details>

```bash
(topaz-0.3.1-python-auto) [guillaume@ANG-KEMI23102LP ~]$ topaz --version
Traceback (most recent call last):
  File "/opt/miniconda3/envs/topaz-0.3.1-python-auto/bin/topaz", line 33, in <module>
    sys.exit(load_entry_point('topaz-em==0.3.1', 'console_scripts', 'topaz')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/topaz-0.3.1-python-auto/lib/python3.12/site-packages/topaz/main.py", line 60, in main
    import topaz.commands.train
  File "/opt/miniconda3/envs/topaz-0.3.1-python-auto/lib/python3.12/site-packages/topaz/commands/train.py", line 8, in <module>
    from topaz.training import load_data,make_model,train_model
  File "/opt/miniconda3/envs/topaz-0.3.1-python-auto/lib/python3.12/site-packages/topaz/training.py", line 15, in <module>
    import topaz.model.classifier as C
  File "/opt/miniconda3/envs/topaz-0.3.1-python-auto/lib/python3.12/site-packages/topaz/model/classifier.py", line 10, in <module>
    from topaz.denoising.datasets import PatchDataset
  File "/opt/miniconda3/envs/topaz-0.3.1-python-auto/lib/python3.12/site-packages/topaz/denoising/datasets.py", line 8, in <module>
    import h5py
ModuleNotFoundError: No module named 'h5py'
```

I installed `h5py` with conda and retried:

```bash
(topaz-0.3.1-python-auto) [guillaume@ANG-KEMI23102LP ~]$ topaz --version
Traceback (most recent call last):
  File "/opt/miniconda3/envs/topaz-0.3.1-python-auto/bin/topaz", line 33, in <module>
    sys.exit(load_entry_point('topaz-em==0.3.1', 'console_scripts', 'topaz')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/topaz-0.3.1-python-auto/lib/python3.12/site-packages/topaz/main.py", line 62, in main
    import topaz.commands.extract
  File "/opt/miniconda3/envs/topaz-0.3.1-python-auto/lib/python3.12/site-packages/topaz/commands/extract.py", line 6, in <module>
    from topaz.extract import extract_particles
  File "/opt/miniconda3/envs/topaz-0.3.1-python-auto/lib/python3.12/site-packages/topaz/extract.py", line 24, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

I installed `tqdm` with conda and retried:

```bash
(topaz-0.3.1-python-auto) [guillaume@ANG-KEMI23102LP ~]$ topaz --version
Traceback (most recent call last):
  File "/opt/miniconda3/envs/topaz-0.3.1-python-auto/bin/topaz", line 33, in <module>
    sys.exit(load_entry_point('topaz-em==0.3.1', 'console_scripts', 'topaz')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/topaz-0.3.1-python-auto/lib/python3.12/site-packages/topaz/main.py", line 66, in main
    import topaz.commands.normalize
  File "/opt/miniconda3/envs/topaz-0.3.1-python-auto/lib/python3.12/site-packages/topaz/commands/normalize.py", line 4, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

I tried installing `imp` with conda, but no such package could be found from the channels `defaults`, `tbepler` and `pytorch`. I tried installing it from `conda-forge`, which completed but replaced several packages with their equivalents from `conda-forge`. But topaz still doesn't work:

```bash
(topaz-0.3.1-python-auto) [guillaume@ANG-KEMI23102LP ~]$ topaz --version
Traceback (most recent call last):
  File "/opt/miniconda3/envs/topaz-0.3.1-python-auto/bin/topaz", line 33, in <module>
    sys.exit(load_entry_point('topaz-em==0.3.1', 'console_scripts', 'topaz')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/topaz-0.3.1-python-auto/lib/python3.12/site-packages/topaz/main.py", line 66, in main
    import topaz.commands.normalize
  File "/opt/miniconda3/envs/topaz-0.3.1-python-auto/lib/python3.12/site-packages/topaz/commands/normalize.py", line 4, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

Very confused by this...

</details>

# Attempt 3

I created a new conda env again, with `python=3`, which today means 3.13. Then I tried installing topaz-0.3.1 with pip:

```bash
conda create -n topaz-0.3.1-pip
conda activate topaz-0.3.1-pip

(topaz-0.3.1-pip) [guillaume@ANG-KEMI23102LP ~]$ pip install topaz-em==0.3.1
Collecting topaz-em==0.3.1
  Using cached topaz_em-0.3.1-py3-none-any.whl.metadata (761 bytes)
Collecting torch>=1.0.0 (from topaz-em==0.3.1)
  Using cached torch-2.5.1-cp313-cp313-manylinux1_x86_64.whl.metadata (28 kB)
INFO: pip is looking at multiple versions of topaz-em to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following yanked versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3
ERROR: Could not find a version that satisfies the requirement torchvision (from topaz-em) (from versions: none)
ERROR: No matching distribution found for torchvision
```

But in this last case, the installation didn't even complete.

# Environment files

Luckily I still have a functioning topaz-0.2.5. I ran `conda env export` on all these environments, attaching them below. The one with topaz-0.2.5 is the only one in which running `topaz --version` doesn't cause a crash (it was installed a while ago, but I believe trying to install the same today would work).

- [topaz-0.2.5_env.txt](https://github.com/user-attachments/files/17937508/topaz-0.2.5_env.txt)
- [topaz-0.3.1-python-3.6_env.txt](https://github.com/user-attachments/files/17937511/topaz-0.3.1-python-3.6_env.txt)
- [topaz-0.3.1-python-auto_env.txt](https://github.com/user-attachments/files/17937513/topaz-0.3.1-python-auto_env.txt)
- [topaz-0.3.1-pip_env.txt](https://github.com/user-attachments/files/17937515/topaz-0.3.1-pip_env.txt)

**Comment by tbepler** [comment]
@Guillawme thanks for flagging this. We'll take a look ASAP.

**Comment by DarnellGranberry** [comment]
I had the same results using conda, so I've updated the readme to specify those versions. Please let us know if you encounter more issues.

**Comment by Guillawme** [comment]
Thank you @DarnellGranberry 

But there is still something I don't understand: shouldn't `conda install topaz -c tbepler -c pytorch`, when run from a freshly created and empty conda environment, figure out automatically which versions of everything will produce a functioning installation? The fact that it does not, with release 0.3.1, suggests to me that you need to update some dependency description file (not familiar enough with Python and conda to know which one) and make a new release to the conda channel.

**Comment by Guillawme** [comment]
This is not sufficient to fix the problem. I just tried this:

```bash
conda create -n topaz-0.3.1 python=3.12
conda activate topaz-0.3.1
conda install topaz -c tbepler -c pytorch
```

Installation completes smoothly, but then I get the same crash:

```bash
(topaz-0.3.1) [guillaume@ANG-KEMI23102LP ~]$ topaz --version
Traceback (most recent call last):
  File "/opt/miniconda3/envs/topaz-0.3.1/bin/topaz", line 33, in <module>
    sys.exit(load_entry_point('topaz-em==0.3.1', 'console_scripts', 'topaz')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/topaz-0.3.1/lib/python3.12/site-packages/topaz/main.py", line 60, in main
    import topaz.commands.train
  File "/opt/miniconda3/envs/topaz-0.3.1/lib/python3.12/site-packages/topaz/commands/train.py", line 8, in <module>
    from topaz.training import load_data,make_model,train_model
  File "/opt/miniconda3/envs/topaz-0.3.1/lib/python3.12/site-packages/topaz/training.py", line 15, in <module>
    import topaz.model.classifier as C
  File "/opt/miniconda3/envs/topaz-0.3.1/lib/python3.12/site-packages/topaz/model/classifier.py", line 10, in <module>
    from topaz.denoising.datasets import PatchDataset
  File "/opt/miniconda3/envs/topaz-0.3.1/lib/python3.12/site-packages/topaz/denoising/datasets.py", line 8, in <module>
    import h5py
ModuleNotFoundError: No module named 'h5py'
```

[topaz-0.3.1-python-3.12.txt](https://github.com/user-attachments/files/17945630/topaz-0.3.1-python-3.12.txt)

**Comment by Guillawme** [comment]
I realized I posted the last two messages during Thanksgiving weekend, and this issue was closed anyway, so pinging @tbepler and @DarnellGranberry just to make sure this doesn't fall through the cracks. Thank you.

**Comment by tbepler** [comment]
Thanks for bumping this. Looks like the issue is that `h5py` is missing from our conda build spec. Weirdly, it has _always_ been missing from the conda build spec so I'm not sure why this worked before.

I suspect the h5py import was on an optional code path that has now become mandatory after the internal refactor and, hence, the lack of h5py never raised an error unless you tried to use the h5py support in topaz denoise training. As far as I know, no one ever used that except for me.

**Comment by gj218** [comment]
Hi,
I am running in the exact same issue today. When I do a clean topaz install into a new environment, the first error message is missing h5py. I install h5py manually in the topaz environment. After that, module tqdm is missing. I install tqdm manually in the topaz environment. After that, I get a more complex error message that seems to complain that there is a version conflict with sympy. Requirement is 1.13.1 but my environment has 1.13.2 installed. The last line in the error message is 'topaz-em==0.3.1 distribution not found'. This may be just from earlier errors.

**Comment by DarnellGranberry** [comment]
Hi @Guillawme @gj218. I've updated the conda spec, and made some other updates. Can you try again?

**Comment by gj218** [comment]
Clean reinstall of version 0.3.4 fails with the same sympy version conflict mentioned before. h5py and tqdm errors no longer occur. This is with python 3.11.

**Comment by Guillawme** [comment]
Hi @DarnellGranberry,

I just tried again and got a similar problem:

```bash
$ conda create -n topaz-0.3.4 python=3.12
$ conda activate topaz-0.3.4
$ conda install topaz -c tbepler -c pytorch
$ topaz --version
Traceback (most recent call last):
  File "/opt/miniconda3/envs/topaz-0.3.4/bin/topaz", line 33, in <module>
    sys.exit(load_entry_point('topaz-em==0.3.4', 'console_scripts', 'topaz')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/topaz-0.3.4/lib/python3.12/site-packages/topaz/main.py", line 66, in main
    import topaz.commands.normalize
  File "/opt/miniconda3/envs/topaz-0.3.4/lib/python3.12/site-packages/topaz/commands/normalize.py", line 4, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

[topaz-0.3.4-env.txt](https://github.com/user-attachments/files/18107954/topaz-0.3.4-env.txt)

**Comment by tbepler** [comment]
I don't think `imp` is actually used anywhere so we can probably just remove this import @DarnellGranberry. It looks like an artifact left over from debugging the internal code refactor.

**Comment by DarnellGranberry** [comment]
@gj218 can you post your full traceback and the outputs of `conda list` and `pip list`?

**Comment by gj218** [comment]
Hope this helps.
[condalist.txt](https://github.com/user-attachments/files/18116795/condalist.txt)
[piplist.txt](https://github.com/user-attachments/files/18116797/piplist.txt)
[rank00000000.log](https://github.com/user-attachments/files/18116798/rank00000000.log)

**Comment by DarnellGranberry** [comment]
@gj218 this looks like the same issues as in #214. I'm assuming you used `conda install topaz -c tbepler -c pytorch` in a fresh environment? Could you try `conda install topaz -c tbepler -c pytorch -c conda-forge`?

**Comment by gj218** [comment]
Same error. I created a fresh environment and then used the conda install you suggested. Only difference is that today the installed sympy version is 1.13.3 and the required version is still 1.13.1. Topaz 0.3.5

**Comment by tbepler** [comment]
I'm trying to diagnose this error. Topaz itself has no dependency on `sympy` and this comes from `pytorch`. It seems like this may be related to an old torch issue [here](https://github.com/pytorch/vision/issues/7034) except that now it's a versioning error on sympy in the pytorch requirements.

Topaz 0.3.5 works after I force install `sympy=1.13.1`  with `conda install sympy==1.13.1`. We could put in a workaround by adding `sympy<=1.13.1` to the build requirements, but it might be fragile since this is actually a `pytorch` dependency.

**Comment by DarnellGranberry** [comment]
I've updated the installation instructions and pinned some versions. Can you please try v0.3.6 with the new instructions?

**Comment by Guillawme** [comment]
Hi @DarnellGranberry 

It seems to be working ok this time! Thank you. :pray: 

I only tried `topaz --version`, which used to crash previously (which prompted me to open this issue), but now works fine. I haven't tried actual commands yet, but this should be fine.

For the record, here is what I did for this last test (installation per the current README's recommendations):

```bash
$ conda create -n topaz-0.3.6 python=3.12
$ conda activate topaz-0.3.6
(topaz-0.3.6) $ topaz --version
0.3.6
(topaz-0.3.6) $ topaz --help
[got the correct output, no crash]
```

Full conda environment that worked correctly: [topaz-0.3.6-env.txt](https://github.com/user-attachments/files/18359433/topaz-0.3.6-env.txt)

**Comment by gj218** [comment]
Works for me. I did a standard install into a clean environment. Topaz job
completed without error.
