### ISSUE TITLE
topaz star_particles_threshold command crashed

### ISSUE THREAD

**Issue by refolding** [tbepler/topaz#7]
Try to use this command to keep particles that have a score >= -2 but it crashed. 

command:
>topaz star_particles_threshold -o particles-t-2.star -t -2 predicted_particles_all_upsampled.star

error message:
Traceback (most recent call last):
  File "/home/conda/apps/conda/envs/topaz/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ParticleScore'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/conda/apps/conda/envs/topaz/bin/topaz", line 11, in <module>
    load_entry_point('topaz==0.1.0', 'console_scripts', 'topaz')()
  File "/home/conda/apps/conda/envs/topaz/lib/python3.6/site-packages/topaz/main.py", line 144, in main
    args.func(args)
  File "/home/conda/apps/conda/envs/topaz/lib/python3.6/site-packages/topaz/commands/star_particles_threshold.py", line 27, in main
    particles['ParticleScore'] = [float(s) for s in particles['ParticleScore']]
  File "/home/conda/apps/conda/envs/topaz/lib/python3.6/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/conda/apps/conda/envs/topaz/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ParticleScore'

**Comment by tbepler** [comment]
In topaz version 0.1.0, "star_particle_threshold" is deprecated in favor of "convert". The "convert" command acts as a catch all for changing particle files between formats but also for scaling particle coordinates and thresholding by score.

```
topaz convert -o particles-t-2.star -t -2 predicted_particles_all_upsampled.star
```
should do what you want.

**Comment by refolding** [comment]
Thanks! That does the trick.
